// Every sound the game can make. Files live in public/audio as name.ogg and name.m4a (generated by
// `npm run audio`, see tools/make-audio.mjs); Phaser loads whichever of the two the browser can play.
//
//   volume          0..1, relative to the master volume
//   overlap         true: each play is its own instance, so quick repeats layer (pickups, hits)
//                   false: one instance, and a new play restarts it (jumps, stings)
//   minIntervalMs   plays closer together than this are dropped
//   pitchVariation  each play is detuned by up to this fraction either way, so repeats do not sound stamped
//   duck            the music drops to DUCK_VOLUME while this plays

export const SOUNDS = {
  jump: { volume: 0.3, overlap: false },
  land: { volume: 0.4, overlap: false },
  stomp: { volume: 0.6, overlap: true, pitchVariation: 0.06 },
  slash: { volume: 0.6, overlap: false },
  'slash-hit': { volume: 0.55, overlap: true, pitchVariation: 0.06 },
  'water-drop': { volume: 0.45, overlap: true, minIntervalMs: 60, pitchVariation: 0.06 },
  'light-orb': { volume: 0.35, overlap: true },
  grow: { volume: 0.5, overlap: false },
  nutrient: { volume: 0.4, overlap: false },
  hurt: { volume: 0.5, overlap: false },
  shrink: { volume: 0.45, overlap: false },
  die: { volume: 0.5, overlap: false },
  'enemy-death': { volume: 0.5, overlap: true },
  'root-rot-split': { volume: 0.6, overlap: true },
  'jar-close': { volume: 0.7, overlap: false },
  'level-complete': { volume: 0.6, overlap: false, duck: true },
  'game-over': { volume: 0.6, overlap: false, duck: true },
  'menu-select': { volume: 0.3, overlap: false },
};

export const MUSIC = {
  level: { file: 'music-level', volume: 0.35 },
  title: { file: 'music-title', volume: 0.4 },
};

export const AUDIO = {
  PATH: 'audio',
  FORMATS: ['ogg', 'm4a'], // in order of preference; Safari plays only the m4a
  DUCK_VOLUME: 0.4, // music volume, as a fraction of its own, while a ducking sound plays
  DUCK_RAMP_MS: 150,
  MUTE_STORAGE_KEY: 'growop.muted',
};
